FROM node:14.18.0-alpine as builder

WORKDIR /

COPY package.json yarn.lock  ./
COPY ../libs libs
COPY ../apps/stripe apps/stripe
RUN yarn

COPY . .
RUN  yarn build:stripe

EXPOSE 4003

CMD [ "yarn", "start:stripe"]